export const production = {"NEXT_PUBLIC_SUPABASE_URL":"","NEXT_PUBLIC_SUPABASE_ANON_KEY":"","SUPABASE_SERVICE_ROLE_KEY":"","CLOUDINARY_CLOUD_NAME":"","CLOUDINARY_API_KEY":"","CLOUDINARY_API_SECRET":""};
export const development = {"NEXT_PUBLIC_SUPABASE_URL":"","NEXT_PUBLIC_SUPABASE_ANON_KEY":"","SUPABASE_SERVICE_ROLE_KEY":"","CLOUDINARY_CLOUD_NAME":"","CLOUDINARY_API_KEY":"","CLOUDINARY_API_SECRET":""};
export const test = {};
